%YAML:1.0
---
yolo_path: "/home/wan/SR_final_v1/SR_radar/model/TensorRT/car.engine"
armor_path: "/home/wan/SR_final_v1/SR_radar/model/TensorRT/armor.engine"
classify_path: "/home/wan/SR_final_v1/SR_radar/model/TensorRT/classify.engine"

# 图像预处理参数
image_preprocess:
  highlight_threshold: 200      # 高光区域的阈值 (0-255)
  highlight_factor: 0.5         # 高光区域亮度降低系数
  contrast_factor: 2.1          # 整体对比度提升系数
  brightness_increase: 50       # 整体亮度提升值
