%YAML:1.0
---
Center_Highland:
        [
                { x: 17.880, y: -2.530, z: 0.3 },
                { x: 12.262, y: -2.530, z: 0.3 },
                { x: 10.150, y: -5.548, z: 0.3 },
                { x: 10.150, y: -9.877, z: 0.3 },
                { x: 10.202, y: -9.999, z: 0.3 },
                { x: 11.209, y: -9.725, z: 0.3 },
                { x: 11.428, y: -10.230, z: 0.3},
                { x: 10.541, y: -10.779, z: 0.3 },
                { x: 10.618, y: -10.958, z: 0.3},
                { x: 10.618, y: -11.758, z: 0.3 },
                { x: 10.119, y: -12.47, z: 0.3},
                { x: 15.738, y: -12.469, z: 0.3 },
                { x: 17.850, y: -9.452, z: 0.3 },
                { x: 17.850, y: -5.123, z: 0.3 },
                { x: 17.798, y: -5.001, z: 0.3 },
                { x: 16.791, y: -5.275, z: 0.3 },
                { x: 16.572, y: -4.770, z: 0.3},
                { x: 17.459, y: -4.221, z: 0.3 },
                { x: 17.382, y: -4.042, z: 0.3},
                { x: 17.382, y: -3.242, z: 0.3 }     
        ]
Self_Highland:
        [
                { x: 9.029, y: -4.050, z: 0.6 },
                { x: 10.032, y: -3.069, z: 0.6 },
                { x: 9.685, y: -2.500, z: 0.6 },
                { x: 5.943, y: -2.500, z: 0.6 },
                { x: 5.943, y: -4.050, z: 0.6 }
        ]
Enemy_Highland:
        [
                { x: 18.971, y: -10.950, z: 0.6 },
                { x: 17.968, y: -11.931, z: 0.6 },
                { x: 18.315, y: -12.500, z: 0.6 },
                { x: 22.057, y: -12.500, z: 0.6 },
                { x: 22.057, y: -10.950, z: 0.6 }
        ]
Right_Road:
        [
                { x: 22.057, y: -12.500, z: 0.6 },
                { x: 18.316, y: -12.500, z: 0.6 },
                { x: 18.316, y: -12.500, z: 0.2 },
                { x: 17.849, y: -12.023, z: 0.2 },
                { x: 17.281, y: -12.775, z: 0.2 },
                { x: 16.153, y: -13.857, z: 0.350 },
                { x: 14.420, y: -13.857, z: 0.350 },
                { x: 13.801, y: -13.860, z: 0.350 },
                { x: 13.801, y: -13.860, z: 0.2 },
                { x: 13.802, y: -13.000, z: 0.2 },
                { x: 15.116, y: -13.000, z: 0.2 },
                { x: 15.738, y: -12.469, z: 0.3 },
                { x: 10.120, y: -12.469, z: 0.3 },
                { x: 9.749, y: -13.000, z: 0.2 }, 
                { x: 6.380, y: -12.850, z: 0.2 },
                { x: 5.783, y: -11.650, z: 0.2 },
                { x: 3.700, y: -11.650, z: 0.2 },
                { x: 3.700, y: -15.000, z: 0.2 },
                { x: 24.975, y: -15.000, z: 0.2 }
        ]
Left_Road:
        [
                { x: 21.620, y: -2.150, z: 0.2 },
                { x: 22.217, y: -3.350, z: 0.2 },
                { x: 24.300, y: -3.350, z: 0.2 },
                { x: 24.300, y: 0.000, z: 0.2 },
                { x: 3.024, y: 0.000, z: 0.2 },
                { x: 3.024, y: -4.050, z: 0.2 },
                { x: 5.498, y: -4.050, z: 0.2 },
                { x: 5.942, y: -4.050, z: 0.6 },
                { x: 5.942, y: -2.500, z: 0.6 },
                { x: 9.684, y: -2.500, z: 0.6 },
                { x: 9.824, y: -2.643, z: 0.8 },
                { x: 11.891, y: -1.143, z: 0.2 },
                { x: 13.580, y: -1.143, z: 0.2 },
                { x: 14.198, y: -1.140, z: 0.2 },
                { x: 14.198, y: -2.000, z: 0.2 },
                { x: 12.884, y: -2.000, z: 0.2 },
                { x: 12.262, y: -2.531, z: 0.3 },
                { x: 17.880, y: -2.531, z: 0.3 },
                { x: 18.251, y: -2.000, z: 0.2 }    
        ]
Self_Fortress:
        [
                { x: 6.310, y: -8.129, z: 0.150 },
                { x: 6.890, y: -8.129, z: 0.150 },
                { x: 7.290, y: -7.436, z: 0.150 },
                { x: 7.000, y: -6.934, z: 0.150 },
                { x: 6.200, y: -6.934, z: 0.150 },
                { x: 5.911, y: -7.436, z: 0.150 }
        ]
Enemy_Fortress:
        [
                { x: 21.690, y: -6.871, z: 0.150 },
                { x: 21.110, y: -6.871, z: 0.150 },
                { x: 20.710, y: -7.564, z: 0.150 },
                { x: 21.000, y: -8.066, z: 0.150 },
                { x: 21.800, y: -8.066, z: 0.150 },
                { x: 22.089, y: -7.564, z: 0.150 }
        ]
