image_width: 3072
image_height: 2048
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [2544.25116,    0.     , 1520.26858,
            0.     , 2543.85302, 1082.40663,
            0.     ,    0.     ,    1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.065712, 0.071142, 0.002361, 0.000441, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [2510.11841,    0.     , 1521.28543,    0.     ,
            0.     , 2518.95435, 1085.71067,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]
